name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"    # every day at midnight UTC
  workflow_dispatch:

permissions:
  contents: write          # allow GITHUB_TOKEN to push commits

concurrency:
  group: snake-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate snake from contributions grid
        uses: Platane/snk@v3.3.0
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Commit and push snake files
        uses: EndBug/add-and-commit@v9
        with:
          add: "dist/*.svg"
          message: "chore(snake): update contribution animation"
          default_author: github_actions
          push: true
